### PR TITLE
release: https://blog.rust-lang.org/2023/02/09/Rust-1.67.1.html

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by jacobgkau** [comment]
`master` is built on arm64 successfully and this branch is not, are we concerned about that?

**Comment by jacobgkau** [comment]
Not a lot of info about why it's failing in the Jenkins log.

```
E: Build failure (dpkg-buildpackage died)
[1mpackaging-rust: dae088cdcb77e9dc2f7dbc8b734c60bf270cc682 (rust): jammy (22.04): arm64: binary failed: exit status: 2[0m
[1mpackaging-rust: dae088cdcb77e9dc2f7dbc8b734c60bf270cc682 (rust): jammy (22.04): binary-arm64 github status failure[0m
```

I don't have an arm64 device, perhaps someone who does could try building locally if that would help.

**Comment by n3m0-22** [comment]
Log from tying to buid on pi400.

[build-error.txt](https://github.com/pop-os/packaging-rust/files/10702952/build-error.txt)

**Comment by 13r0ck** [comment]
lol of course Clippy killed it :laughing:

**Comment by n3m0-22** [comment]
clippy

**Review by jackpot51 — APPROVED** [review]

**Review by n3m0-22 — APPROVED** [review]
Updated `rustc` and `cargo` installed and are working. I confirmed `arm64` with `pi400`.

**Pull request merged**
