### PR TITLE
Rust 1.80.0

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jacobgkau — CHANGES_REQUESTED** [review]
I'm getting an error trying to run rustc on Pop!_OS 22.04:

```
system76@pop-os:~/test1$ rustc -V
rustc: error while loading shared libraries: libLLVM.so.18.1-rust-1.80.0-stable: cannot open shared object file: No such file or directory
```

**Review by jacobgkau — CHANGES_REQUESTED** [review]
`rustc` is working now. However, after installing the new `rustfmt` package and attempting to run that, it gives the same shared library error that `rustc` did before.

```
system76@pop-os:~/test1$ rustfmt
rustfmt: error while loading shared libraries: libLLVM.so.18.1-rust-1.80.0-stable: cannot open shared object file: No such file or directory
```

**Review by jacobgkau — CHANGES_REQUESTED** [review]
cargo, rustc, and rustfmt are all working as expected now.

I tried running the executables installed by the new `rust-clippy` package, and `cargo-clippy` still gives the library error:

```
system76@pop-os:~/test1$ apt policy rust-clippy
rust-clippy:
  Installed: 1.80.0~1722326098~22.04~d258a11
  Candidate: 1.80.0~1722326098~22.04~d258a11
  Version table:
 *** 1.80.0~1722326098~22.04~d258a11 1002
       1002 http://apt.pop-os.org/staging/rust jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     1.75.0+dfsg0ubuntu1~bpo0-0ubuntu0.22.04 500
        500 http://apt.pop-os.org/ubuntu jammy-security/universe amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 Packages
     1.58.1+dfsg1~ubuntu1-0ubuntu2 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
system76@pop-os:~/test1$ cargo-clippy
cargo-clippy: error while loading shared libraries: libLLVM.so.18.1-rust-1.80.0-stable: cannot open shared object file: No such file or directory
```

I'm assuming that means it also needs the patchelf fix.

**Review by jacobgkau — CHANGES_REQUESTED** [review]
Still getting the library error running `cargo-clippy` on commit e21088c.

```
system76@pop-os:~/test1$ apt policy rust-clippy
rust-clippy:
  Installed: 1.80.0~1722331824~22.04~e21088c
  Candidate: 1.80.0~1722331824~22.04~e21088c
  Version table:
 *** 1.80.0~1722331824~22.04~e21088c 1002
       1002 http://apt.pop-os.org/staging/rust jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     1.75.0+dfsg0ubuntu1~bpo0-0ubuntu0.22.04 500
        500 http://apt.pop-os.org/ubuntu jammy-security/universe amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 Packages
     1.58.1+dfsg1~ubuntu1-0ubuntu2 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
system76@pop-os:~/test1$ cargo-clippy --version
cargo-clippy: error while loading shared libraries: libLLVM.so.18.1-rust-1.80.0-stable: cannot open shared object file: No such file or directory
system76@pop-os:~/test1$ 
```

**Comment by mmstick** [comment]
I see that I wrote clippy-driver instead of cargo-clippy

**Review by jacobgkau — APPROVED** [review]
`cargo-clippy` works now. `clippy-driver` still works, as do `cargo`, `rustc`, and `rustfmt`.

**Pull request merged**
