### PR TITLE
release: https://blog.rust-lang.org/2023/07/13/Rust-1.71.0.html

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
Do we know why the arm64 build isn't completing? It looks like it's successful on master and on previous PRs.

**Comment by mmstick** [comment]
The build log is gone so it must have finished without reporting the status. Perhaps an issue on GitHub's side at the time.

**Comment by jacobgkau** [comment]
Ah, the arm64 build does appear to be in the staging branch.

**Review by jacobgkau — APPROVED** [review]
Installs and runs fine.

**Pull request merged**
